[en]
  title = "Flipping Flips"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[ko]
  title = "Flipping Flips"
  languageName = "한국어"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/ko"
